version: '3.3'

services: 
    kanban_gateway:
        image: devopsfaith/krakend
        ports: 
            - "${PORT}:9091"
            - "8090:8090"
        environment: 
            - INFLUXDB_BUCKET_NAME=${INFLUXDB_BUCKET_NAME}
            - INFLUXDB_HOST=${INFLUXDB_HOST}
            - INFLUXDB_PORT=${INFLUXDB_PORT}
            - INFLUXDB_USER=${INFLUXDB_USER}
            - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
        volumes: 
            - ./config.json:/etc/krakend/krakend.json
        networks:
            - kanban

    zipkin:
        image: openzipkin/zipkin
        ports: 
            - "${ZIPKIN_PORT}:9411"
        networks:
            - kanban

    rabbit-mq:
        image: rabbitmq:3-management
        hostname: ${HOSTNAME}
        ports: 
            - "${RABBITMQ_FST_PORT}:15672"
            - "${RABBITMQ_SND_PORT}:5672"
        networks:
            - kanban

networks:
  kanban:
      driver: overlay
      attachable: true
